
#RIOTBASE ?=/home/ipa/jingwei/teamproject/RIOT_eisV

#CFLAGS ?= -Os -g -static -mabi=ilp32 -march=rv32im -Wall -pedantic

include $(RIOTBASE)/Makefile.base

CFLAGS += -Wno-unused-parameter -Wno-strict-prototypes -Wno-old-style-definition
